### ISSUE TITLE
Во время сборки на CI/CD падает на ошибке /.werf/stapel/embedded/bin/bash: /.werf/ansible-workdir/ansible-playbook: No such file or directory

### ISSUE THREAD

**Issue by skyfall174** [flant/werf#1462]
Когда собираю локально у себя на компьютере все работает отлично, как только тот же самый билд кидаю в gitlab (CI/CD) падает на ошибке

 ```
Building stage beforeInstall
│ │ │ ~/beforeInstall  /.werf/stapel/embedded/bin/bash: /.werf/ansible-workdir/ansible-playbook: No such file or directory
│ │ ├ Info
│ │ └ Building stage beforeInstall (0.80 seconds) FAILED
│ └ ⛵ image ~ (0.80 seconds) FAILED
└ Building stages (0.80 seconds) FAILED
```

Вот кусок стадии before_install

```
ansible:
  beforeInstall:
    - name: Install composer
      get_url:
        url: https://getcomposer.org/download/1.6.5/composer.phar
        dest: /usr/local/bin/composer
        mode: a+x

    - name: "Install PHP and modules"
      apt:
        name: "{{`{{ item }}`}}"
        state: present
        update_cache: yes
      with_items:
        - libldb-dev
        - libldap2-dev
        - libpq-dev
        - libxml++2.6-dev
        - zlib1g-dev
        - libzip-dev
        - libpng-dev

    - name: Create apache group
      group:
        name: apache
    - name: Create apache user
      user:
        name: apache
        group: apache
    - name: Configure PHP extensions
      command: docker-php-ext-install zip gd ldap pdo pgsql soap

```

.gitlab-ci.yml:

```
BuildDockerImage:
  image: skyfall174/werf-ci:latest
  services:
    - docker:dind
  tags:
    - werf
  stage: docker
  script:
    - cat werf.yaml
    - source <(/root/bin/multiwerf use 1.0 beta)
    - type werf && source <(werf ci-env gitlab --tagging-strategy tag-or-branch --verbose)
    - werf build --stages-storage :local

```

образ [skyfall174/werf-ci:latest Dockerfile ](https://github.com/skyfall174/werf-ci)
