### ISSUE TITLE
/.dapp/deps/base/0.2.3/embedded/bin/bash:  apk: command not found

### ISSUE THREAD

**Issue by tempdos** [flant/werf#1477]
[Исходник](https://github.com/flant/werf/files/3090306/werf.yaml.txt)

**Comment by flant-team-sysdev** [comment]
werf version please

**Comment by alexey-igrychev** [comment]
Issue tittle relates with dapp (`dappfile.yaml`) but source is `werf.yaml`, is it correct?

**Comment by distorhead** [comment]
Bad syntax provided. Yaml does not support backslashes to wrap long lines. Should be:

```yaml
project: chebdik 
configVersion: 1
---
image: ~
from: alpine:3.7
shell:
  beforeInstall:
  - |
    echo "@community http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories &&
    apk update &&
    apk add mysql mysql-client
```

Or (better):

```yaml
project: chebdik 
configVersion: 1
---
image: ~
from: alpine:3.7
shell:
  beforeInstall:
  - echo "@community http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
  - apk update
  - apk add mysql mysql-client
```
