### ISSUE TITLE
Run migrations for database schema

### ISSUE THREAD

**Issue by lionskape** [flant/werf#1607]
Hello, what is canonical way to run migrations for db schema with werf?

**Comment by distorhead** [comment]
Hi!

There are 2 known possible ways.

### `pre-upgrade` helm hook

https://github.com/helm/helm/blob/master/docs/charts_hooks.md#the-available-hooks

Suitable for the migrations, not suitable for the initial database bootstrap when installing release.

### Simple Job

Use simple Job (not helm hook) with a random name for each rollout. Werf will by default track all jobs of the release till ready. For example Job may look like this:

```
{{ $jobId := randAlpha 5 | lower  }}

apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-{{ $jobId }}
spec:
  activeDeadlineSeconds: 6000
  template:
    metadata:
      name: migrate-{{ $jobId }}
    spec:
      restartPolicy: OnFailure
      containers:
      - name: migrate
        image: ubuntu:18.04
        command: [ '/bin/bash', '-l', '-c', 'for i in {1..20} ; do date; sleep 1 ; done' ]
```

On each rollout helm will create a new Job with a random name. And also helm will detect, that previous Job have gone from the release and will cleanup resource from kubernetes automatically.

Some resource (e.g. Deployment) may need migrated database state to start up properly. In this case werf resources tracker should ignore errors from this resource until migrate Job is done. To specify werf to ignore errors from some resource use `"werf.io/fail-mode": HopeUntilEndOfDeployProcess`  annotation:

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mydeploy22
  annotations:
    "werf.io/fail-mode": HopeUntilEndOfDeployProcess
  labels:
    service: mydeploy22
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: mydeploy22
    spec:
      containers:
      - name: main
        command: [ "/bin/bash", "-c", "while true; do date ; sleep 1 ; done" ]
        image: ubuntu:18.04
```


In the future we will add arbitrary deploy stages to control rollout process.
