### ISSUE TITLE
Ansible error: file name too long

### ISSUE THREAD

**Issue by distorhead** [flant/werf#1713]
```
│ │ │ backend-build/install   [WARNING]: Failure using method (v2_playbook_on_play_start) in callback plugin
│ │ │ backend-build/install  (<ansible.plugins.callback.werf.CallbackModule object at 0x7f16d04d78d0>):
│ │ │ backend-build/install  [Errno 36] File name too long
```

**Comment by distorhead** [comment]
```
│ │ │ backend-build/install   [WARNING]: Failure using method (v2_playbook_on_stats) in callback plugin
│ │ │ backend-build/install  (<ansible.plugins.callback.werf.CallbackModule object at 0x7f16d04d78d0>):
│ │ │ backend-build/install  'LiveStdoutListener' object has no attribute '_reader'
│ │ │ backend-build/install
```

**Comment by distorhead** [comment]
```
artifact: backend-build
from: php:7.3-cli-alpine3.10
ansible:
  beforeInstall:
    - name: Install Composer
      get_url:
        url: https://getcomposer.org/download/1.8.6/composer.phar
        dest: /usr/bin/composer
        mode: a+x
        owner: www-data
  install:
    - name: Install Composer dependencies
      shell: composer install --ignore-platform-reqs
      become: yes
      become_user: www-data
      args:
        chdir: /app/
git:
  - add: /
    to: /app
    owner: www-data
    group: www-data
    stageDependencies:
      install:
        - composer.json
        - composer.lock
```
