### ISSUE TITLE
[stapel image] warning: unable to access '/root/.config/git/attributes': Permission denied

### ISSUE THREAD

**Issue by alexey-igrychev** [flant/werf#1771]
The steps to reproduce:

werf.yaml:
```
project: test
configVersion: 1.0
---
image: ~
from: ubuntu:16.04
git:
- to: /app
  owner: app
  group: app
shell:
  beforeInstall: useradd -U app
```

1. `werf build -s=:local`
2. Commit any changes and build again
