### ISSUE TITLE
PATH is redefined in the stapel build container

### ISSUE THREAD

**Issue by distorhead** [flant/werf#1836]
```
artifact: app
from: golang:1.12-alpine3.9
git:
- add: /app
  to: /app
  excludePaths:
  - development
  stageDependencies:
    install:
    - go.mod
    - go.sum
    setup:
    - "**/*.go"
    - go-build.sh
ansible:
  beforeInstall:
  - apk: name=git update_cache=yes
  - command: rm -rf /var/cache/apk/*

  install:
  - shell: go mod download
    args:
      chdir: /app
```

Results in errors like:

```
│ │ ┌ Building stage install
│ │ │ app/install  ┌ command [go mod download]
│ │ │ app/install  │ [Errno 2] No such file or directory
│ │ │ app/install  │ exit code: 2
│ │ │ app/install  └ command [go mod download] (0.76 seconds) FAILED
```
