### ISSUE TITLE
Unpredictable imports behaviour when importing file: depends on base image

### ISSUE THREAD

**Issue by distorhead** [flant/werf#2192]
Given following config:

```
import:
- artifact: myartifact
  add: /path/to/myfile
  to: /new/path
```

If `/new/path` is existing directory in the base image, then `/new/path/myfile` will be created.
If `/new/path` does not exist in the base image, then `/new/path` file will be created with the content of `/path/to/myfile`.

Expected more declarative behaviour: always create `/new/path` with the content of the `/path/to/myfile`.  In the case when `/new/path` is existing directory werf should exit with error.
