### ISSUE TITLE
Add ability to reset gitArchive stage

### ISSUE THREAD

**Issue by distorhead** [flant/werf#2248]
As a devops engineer I want to have an ability to reset gitArchive stage cache from `werf.yaml` config.

There should be a `gitCacheVersion: STRING` directive:

```
gitCacheVersion: STRING
git:
- add: /...
  to: /...
```

`gitCacheVersion` should affect `gitArchive` stage signature. This stage will be rebuilt on `gitCacheVersion` change.

**Comment by borgius** [comment]
workaround for now: we can add excludePaths with any fake filename:
```yaml
git:
  - add: /
    to: /app
    excludePaths:
      - "gitCacheVersion_1"

```
