### ISSUE TITLE
v1.1 constantly rebuild gitArchive stage when multiple git mappings by the same url are defined

### ISSUE THREAD

**Issue by distorhead** [flant/werf#2407]
The following config:

```
project: bug-with-remote-git
configVersion: 1
---
image: ~
from: ubuntu:18.04
git:
- url: https://github.com/flant/werf.git
  to: /one
  tag: v1.0.13
- url: https://github.com/flant/werf.git
  to: /two
  commit: 892db788d03ec7e170dbd7cf04e46edd8e7742a0
```

— will rebuild stage `~/gitArchive` on every werf build invocation (using any stages-storage: local or docker registry)
