### ISSUE TITLE
Unnecessary fetch of external git specified by url

### ISSUE THREAD

**Issue by distorhead** [flant/werf#2454]
When git mapping that uses external git repo by url has been specified and `commit` or `tag` directive used werf will fetch this repo on every build, which is unncesessary and time consuming.

```
git:
- add: /
  to: /app
  url: https://github.com/flant/werf
  commit|tag: X
```
