### ISSUE TITLE
apt module hangs on debian 7 jessie

### ISSUE THREAD

**Issue by diafour** [flant/werf#645]
`dapp dimg build` hangs forever when using jessie as base image and apt module.

Minimal dappfile.yml to reproduce :
```yaml
from: python:3.6-jessie
ansible:
  beforeInstall:
  - apt: update_cache=yes
```

`python:3.6-stretch` is OK
